on:
  push:
    branches:
      - '!main'
    paths:
      - '**/*.svelte'
      - '**/*.ts'
      - '**/*.json'
      - '**/build-test.yml'
  pull_request:
    paths:
      - '**/*.svelte'
      - '**/*.ts'
      - '**/*.json'
      - '**/build-test.yml'

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          run_install: false
          version: 8
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - run: pnpm install

      - run: pnpm build

      - name: test with curl
        run: |
          pnpm preview &
          sleep 5
          curl -v http://localhost:4173s/ -I

      - name: Send Failure to discord
        if: failure()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_EMBEDS: |
            '{
              "embeds": [{
                  "title": "Failed build test",
                  "color": 14177041,
                  "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                }]
              }'
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: 'üêí'

  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          run_install: false
          version: 8
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - run: pnpm install

      - run: pnpm build

      - name: start server
        run: |
          pnpm preview &
          sleep 5

      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v10
        with:
          urls: |
            http://localhost:4173/
            http://localhost:4173/en
          budgetPath: ./budget.json # test performance budgets
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage

      - name: Send Failure to discord
        if: ${{ failure() }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_EMBEDS: |
            '{
              "embeds": [{
                  "title": "Failed build test", 
                  "color": 14177041, 
                  "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                }]
              }'
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: 'üêí'
